/*const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 15.99,
    img: './images/item-1.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 13.99,
    img: './images/item-2.jpeg',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 6.99,
    img: './images/item-3.jpeg',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 20.99,
    img: './images/item-4.jpeg',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 22.99,
    img: './images/item-5.jpeg',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: './images/item-6.jpeg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 8.99,
    img: './images/item-7.jpeg',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 12.99,
    img: './images/item-8.jpeg',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 16.99,
    img: './images/item-9.jpeg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];*/

const menu2 = [{
        id: 1,
        imgUrl: "https://media.ex-cdn.com/EXP/media.vntravellive.com/files/editor1/2018/12/07/5517-di-dau-de-tim-thay-pizza-ngon-nhat-105446.jpg",
        name: "PIZZA MIXED",
        category: "PIZZA",
        pricePU: 4.8,
        desc: `I'm baby`,
    },
    {
        id: 2,
        imgUrl: "https://media.ex-cdn.com/EXP/media.vntravellive.com/files/editor1/2018/12/07/5517-di-dau-de-tim-thay-pizza-ngon-nhat-105446.jpg",
        name: "PIZZA MIXED",
        category: "PIZZA",
        pricePU: 4.8,
        desc: `I'm baby`,
    },
    {
        id: 3,
        imgUrl: "https://media.ex-cdn.com/EXP/media.vntravellive.com/files/editor1/2018/12/07/5517-di-dau-de-tim-thay-pizza-ngon-nhat-105446.jpg",
        name: "PIZZA MIXED",
        category: "PIZZA",
        pricePU: 4.8,
        desc: `I'm baby`,
    },
    {
        id: 4,
        imgUrl: "https://media.ex-cdn.com/EXP/media.vntravellive.com/files/editor1/2018/12/07/5517-di-dau-de-tim-thay-pizza-ngon-nhat-105446.jpg",
        name: "PIZZA MIXED",
        category: "PIZZA",
        pricePU: 4.8,
        desc: `I'm baby`,
    },
    {
        id: 5,
        imgUrl: "https://media.ex-cdn.com/EXP/media.vntravellive.com/files/editor1/2018/12/07/5517-di-dau-de-tim-thay-pizza-ngon-nhat-105446.jpg",
        name: "PIZZA MIXED",
        category: "PIZZA",
        pricePU: 4.8,
        desc: `I'm baby`,
    },
    {
        id: 6,
        imgUrl: "http://farm1.staticflickr.com/955/41117503084_128499c414.jpg",
        name: "BURGER MIXED",
        category: "BURGER",
        pricePU: 4.8,
        desc: `I'm baby`,
    },
    {
        id: 7,
        imgUrl: "http://farm1.staticflickr.com/955/41117503084_128499c414.jpg",
        name: "BURGER MIXED",
        category: "BURGER",
        pricePU: 4.8,
        desc: `I'm baby`,
    },
    {
        id: 8,
        imgUrl: "http://farm1.staticflickr.com/955/41117503084_128499c414.jpg",
        name: "BURGER MIXED",
        category: "BURGER",
        pricePU: 4.8,
        desc: `I'm baby`,
    },
    {
        id: 9,
        imgUrl: "http://farm1.staticflickr.com/955/41117503084_128499c414.jpg",
        name: "BURGER MIXED",
        category: "BURGER",
        pricePU: 4.8,
        desc: `I'm baby`,
    },
    {
        id: 10,
        imgUrl: "http://farm1.staticflickr.com/955/41117503084_128499c414.jpg",
        name: "BURGER MIXED",
        category: "BURGER",
        pricePU: 4.8,
        desc: `I'm baby`,
    },
    {
        id: 11,
        imgUrl: "https://images.startsat60.com/wp-content/uploads/20150801171559/310715_pumpkin_soup-500x281.jpg",
        name: "SOUP MIXED",
        category: "SOUP",
        pricePU: 4.8,
        desc: `I'm baby`,
    },
    {
        id: 12,
        imgUrl: "https://images.startsat60.com/wp-content/uploads/20150801171559/310715_pumpkin_soup-500x281.jpg",
        name: "SOUP MIXED",
        category: "SOUP",
        pricePU: 4.8,
        desc: `I'm baby`,
    },
    {
        id: 13,
        imgUrl: "https://images.startsat60.com/wp-content/uploads/20150801171559/310715_pumpkin_soup-500x281.jpg",
        name: "SOUP MIXED",
        category: "SOUP",
        pricePU: 4.8,
        desc: `I'm baby`,
    },
    {
        id: 14,
        imgUrl: "https://images.startsat60.com/wp-content/uploads/20150801171559/310715_pumpkin_soup-500x281.jpg",
        name: "SOUP MIXED",
        category: "SOUP",
        pricePU: 4.8,
        desc: `I'm baby`,
    },
    {
        id: 15,
        imgUrl: "https://images.startsat60.com/wp-content/uploads/20150801171559/310715_pumpkin_soup-500x281.jpg",
        name: "SOUP MIXED",
        category: "SOUP",
        pricePU: 4.8,
        desc: `I'm baby`,
    },
    {
        id: 16,
        imgUrl: "https://nghekhachsan.com/upload/Ni-Anh-NKS/Nam-2019/Thang-11/cong-thuc-pha-tra-dao-01.jpg",
        name: "PEACH TEA",
        category: "TEA",
        pricePU: 4.8,
        desc: `I'm baby`,
    },
    {
        id: 17,
        imgUrl: "https://nghekhachsan.com/upload/Ni-Anh-NKS/Nam-2019/Thang-11/cong-thuc-pha-tra-dao-01.jpg",
        name: "PEACH TEA",
        category: "TEA",
        pricePU: 4.8,
        desc: `I'm baby`,
    },
    {
        id: 18,
        imgUrl: "https://nghekhachsan.com/upload/Ni-Anh-NKS/Nam-2019/Thang-11/cong-thuc-pha-tra-dao-01.jpg",
        name: "PEACH TEA",
        category: "TEA",
        pricePU: 4.8,
        desc: `I'm baby`,
    },
    {
        id: 19,
        imgUrl: "https://nghekhachsan.com/upload/Ni-Anh-NKS/Nam-2019/Thang-11/cong-thuc-pha-tra-dao-01.jpg",
        name: "PEACH TEA",
        category: "TEA",
        pricePU: 4.8,
        desc: `I'm baby`,
    },
    {
        id: 20,
        imgUrl: "https://nghekhachsan.com/upload/Ni-Anh-NKS/Nam-2019/Thang-11/cong-thuc-pha-tra-dao-01.jpg",
        name: "PEACH TEA",
        category: "TEA",
        pricePU: 4.8,
        desc: `I'm baby`,
    },

    {
        id: 21,
        imgUrl: "https://hallmark.brightspotcdn.com/dims4/default/5beba82/2147483647/strip/true/crop/500x281+0+0/resize/1140x640!/quality/90/?url=http%3A%2F%2Fhallmark-channel-brightspot.s3.amazonaws.com%2Fa2%2F24%2Fc5371a577db4a441383a914b79b8%2Fhf-ep2111-product-cristina-cooks.jpg",
        name: "CAKE",
        category: "OTHER",
        pricePU: 4.8,
        desc: `I'm baby`,
    },
    {
        id: 22,
        imgUrl: "https://www.cookingpanda.com/wp-content/uploads/2021/04/0004_16x9_CandyCookieCake-500x281.jpg",
        name: "COFFEE CAKE",
        category: "OTHER",
        pricePU: 4.8,
        desc: `I'm baby`,
    },
    {
        id: 23,
        imgUrl: "https://jandatri.com/wp-content/uploads/2019/02/Black-Forest-Cake-Slice-500x281.jpg",
        name: "TIRAMISU CAKE",
        category: "OTHER",
        pricePU: 4.8,
        desc: `I'm baby`,
    },
    {
        id: 24,
        imgUrl: "https://i.ndtvimg.com/i/2016-04/granola-parfait-625_625x350_41459499249.jpg",
        name: "STRAWBERRY ICE-DREAM",
        category: "OTHER",
        pricePU: 4.8,
        desc: `I'm baby`,
    },
    {
        id: 25,
        imgUrl: "https://i.ndtvimg.com/i/2016-04/granola-parfait-625_625x350_41459499249.jpg",
        name: "STRAWBERRY ICE-DREAM",
        category: "OTHER",
        pricePU: 4.8,
        desc: `I'm baby`,
    },
];
export default menu2;